<?php

declare(strict_types=1);

/**
 * CMS ACC API — Single entry point.
 *
 * Routes:
 *   POST /request-access → Perusal score magic-link request
 *   POST /verify-token   → Token verification
 *   POST /contact        → Contact form submission
 *
 * Deploy: point your web server's document root at this `public/` directory.
 */

require_once __DIR__ . '/../vendor/autoload.php';

use CmsAcc\ContactHandler;
use CmsAcc\Cors;
use CmsAcc\DownloadHandler;
use CmsAcc\NewsletterHandler;
use CmsAcc\PerusalHandler;
use CmsAcc\SubmissionHandler;

// ─── Load environment ────────────────────────────────────────────────────────

// Load both .env (secrets) and .env.validation (form constraints derived from YAML).
// .env.validation is auto-generated by scripts/generate-api-config.mjs.
// safeLoad() silently skips any file that does not exist.
// shortCircuit=false (3rd arg) ensures BOTH files are loaded — the default (true)
// stops after the first file found, which would skip .env.validation entirely.
$dotenv = Dotenv\Dotenv::createImmutable(__DIR__ . '/..', ['.env', '.env.validation'], false);
$dotenv->safeLoad();

// ─── CORS ────────────────────────────────────────────────────────────────────

Cors::handlePreflight();
Cors::addHeaders();

// ─── Parse request ───────────────────────────────────────────────────────────

$method = $_SERVER['REQUEST_METHOD'] ?? 'GET';
$uri    = parse_url($_SERVER['REQUEST_URI'] ?? '/', PHP_URL_PATH);

// Strip base path if the app is deployed in a subdirectory.
// e.g., /api/request-access → /request-access
$basePath = rtrim($_ENV['BASE_PATH'] ?? '', '/');
if ($basePath !== '' && str_starts_with($uri, $basePath)) {
    $uri = substr($uri, strlen($basePath));
}

$uri = '/' . ltrim($uri, '/');

// ─── JSON body ───────────────────────────────────────────────────────────────

$body = [];
if ($method === 'POST') {
    $raw = file_get_contents('php://input');
    if ($raw !== false && $raw !== '') {
        $parsed = json_decode($raw, true);
        if (is_array($parsed)) {
            $body = $parsed;
        }
    }
}

// ─── Router ──────────────────────────────────────────────────────────────────

$response = match (true) {
    $method === 'POST' && $uri === '/request-access'  => PerusalHandler::requestAccess($body),
    $method === 'POST' && $uri === '/verify-token'    => PerusalHandler::verifyToken($body),
    $method === 'POST' && $uri === '/contact'         => ContactHandler::handle($body),
    $method === 'GET'  && $uri === '/download-score'  => DownloadHandler::handle(),

    // Newsletter.
    $method === 'POST' && $uri === '/newsletter/send'                 => NewsletterHandler::send($body),
    $method === 'GET'  && $uri === '/newsletter/subscribers'           => NewsletterHandler::listSubscribers(),
    $method === 'GET'  && $uri === '/newsletter/subscribers/detail'    => NewsletterHandler::subscriberDetail(),
    $method === 'POST' && $uri === '/newsletter/subscribers/delete'    => NewsletterHandler::deleteSubscribers($body),
    $method === 'POST' && $uri === '/newsletter/subscribers/update'    => NewsletterHandler::updateSubscriber($body),

    // Submissions admin.
    $method === 'GET'  && $uri === '/submissions'          => SubmissionHandler::listSubmissions(),
    $method === 'GET'  && $uri === '/submissions/detail'   => SubmissionHandler::submissionDetail(),
    $method === 'POST' && $uri === '/submissions/delete'   => SubmissionHandler::deleteSubmissions($body),

    // Unsubscribe (GET for browser, POST for RFC 8058 one-click).
    $method === 'GET'  && $uri === '/unsubscribe'    => NewsletterHandler::unsubscribe(),
    $method === 'POST' && $uri === '/unsubscribe'    => NewsletterHandler::unsubscribePost($body),

    // Health check (useful for uptime monitoring).
    $method === 'GET' && $uri === '/health'           => ['status' => 200, 'body' => ['ok' => true, 'version' => '1.0.1']],

    // Catch-all.
    default => ['status' => 404, 'body' => ['error' => 'Not found']],
};

// ─── Send response ───────────────────────────────────────────────────────────

// status=0 signals that the handler already sent its own response (e.g. file stream).
if ($response['status'] !== 0) {
    http_response_code($response['status']);
    header('Content-Type: application/json; charset=utf-8');
    header('Cache-Control: no-store');

    echo json_encode($response['body'], JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);
}
