// THIS FILE IS AUTO-GENERATED BY scripts/generate-perusal-scores.mjs
// Run: node ./scripts/generate-perusal-scores.mjs

/** Map of work slug → number of perusal score pages */
const perusalScores: Record<string, number> = {}

/** Map of work slug → per-page cache-busting hashes for perusal score images */
const perusalScorePageHashes: Record<string, string[]> = {}

export default perusalScores
export { perusalScorePageHashes }
