// THIS FILE IS AUTO-GENERATED BY scripts/generate-works-images.mjs
// Run: node ./scripts/generate-works-images.mjs

import type { ImageMetadata } from 'astro'

const worksImages: { data: ImageMetadata; path: string; filename: string }[] = []

export default worksImages
