// THIS FILE IS AUTO-GENERATED BY scripts/generate-page-search-index.mjs
// Run: node ./scripts/generate-page-search-index.mjs

import type { SearchablePageItem } from '../scripts/search-types'

export const generatedPageSearchEntries: SearchablePageItem[] = []
